"""PlatformIO pre-build step: compile the selected NeXus JSON profile into C++ constants."""

from __future__ import annotations

import json
from hashlib import sha256
from pathlib import Path

Import("env")  # type: ignore[name-defined]  # PlatformIO/SCons injects this symbol.


def cpp_string(value: object) -> str:
    return json.dumps(str(value), ensure_ascii=True)


def number(value: object) -> str:
    rendered = format(float(value), ".12g")
    return rendered if "." in rendered else f"{rendered}.0"


project_dir = Path(env["PROJECT_DIR"]).resolve()  # type: ignore[name-defined]
configured_path = env.GetProjectOption("custom_nexus_hardware_profile")  # type: ignore[name-defined]
profile_path = (project_dir / configured_path).resolve()
profile = json.loads(profile_path.read_text(encoding="utf-8"))
canonical_profile = json.dumps(
    profile,
    ensure_ascii=False,
    sort_keys=True,
    separators=(",", ":"),
).encode("utf-8")
profile_sha256 = sha256(canonical_profile).hexdigest()

required = {"schema_version", "profile_id", "hardware_model_id", "controller", "transport", "safety", "firmware"}
missing = required - profile.keys()
if missing:
    raise ValueError(f"NeXus hardware profile is missing: {', '.join(sorted(missing))}")

firmware = profile["firmware"]
pins = firmware["pins"]
sensor = firmware["sensor"]
identity = sensor["identity"]
safety = profile["safety"]
baud_rate = profile["transport"].get("baud_rate", 115200)

pin_id = lambda value: cpp_string(f"gpio_{value}")
content = f"""// Generated from {profile_path.name}. Do not edit this file by hand.
#pragma once

#define NEXUS_HARDWARE_PROFILE_SCHEMA_VERSION {cpp_string(profile['schema_version'])}
#define NEXUS_HARDWARE_PROFILE_ID {cpp_string(profile['profile_id'])}
#define NEXUS_HARDWARE_PROFILE_SHA256 {cpp_string(profile_sha256)}
#define NEXUS_HARDWARE_PROFILE_VERSION {cpp_string(firmware['profile_version'])}
#define NEXUS_HARDWARE_MODEL_ID {cpp_string(profile['hardware_model_id'])}
#define NEXUS_CONTROLLER_MODEL {cpp_string(profile['controller']['model'])}
#define NEXUS_CONTROLLER_BOARD_ID {cpp_string(profile['controller']['board_id'])}
#define NEXUS_SENSOR_PROFILE {cpp_string(firmware['sensor_profile'])}
#define NEXUS_DRIVER_PROFILE {cpp_string(firmware['driver_profile'])}
#define NEXUS_SERIAL_BAUD_RATE {int(baud_rate)}

#define NEXUS_I2C_SDA_PIN {int(pins['i2c_sda'])}
#define NEXUS_I2C_SCL_PIN {int(pins['i2c_scl'])}
#define NEXUS_MOTOR_ENABLE_PIN {int(pins['motor_enable'])}
#define NEXUS_MOTOR_IN1_PIN {int(pins['motor_in1'])}
#define NEXUS_MOTOR_IN2_PIN {int(pins['motor_in2'])}
#define NEXUS_ENCODER_A_PIN {int(pins['encoder_a'])}
#define NEXUS_ENCODER_B_PIN {int(pins['encoder_b'])}
#define NEXUS_MOTOR_ENABLE_PIN_ID {pin_id(pins['motor_enable'])}
#define NEXUS_MOTOR_IN1_PIN_ID {pin_id(pins['motor_in1'])}
#define NEXUS_MOTOR_IN2_PIN_ID {pin_id(pins['motor_in2'])}
#define NEXUS_ENCODER_A_PIN_ID {pin_id(pins['encoder_a'])}
#define NEXUS_ENCODER_B_PIN_ID {pin_id(pins['encoder_b'])}

#define NEXUS_SENSOR_I2C_ADDRESS {int(sensor['i2c_address'], 16)}
#define NEXUS_SENSOR_SHUNT_OHMS {number(sensor['shunt_ohms'])}f
#define NEXUS_SENSOR_CURRENT_LSB_MA {number(sensor['current_lsb_ma'])}f
#define NEXUS_SENSOR_MANUFACTURER_ID {int(identity['manufacturer_id'], 16)}
#define NEXUS_SENSOR_DIE_ID {int(identity['die_id'], 16)}
#define NEXUS_SENSOR_DIE_ID_MASK {int(identity['die_id_mask'], 16)}

#define NEXUS_MIN_BUS_VOLTAGE_MV {round(float(safety['min_bus_voltage_v']) * 1000)}
#define NEXUS_MAX_BUS_VOLTAGE_MV {round(float(safety['max_bus_voltage_v']) * 1000)}
#define NEXUS_MAX_CURRENT_MA {number(safety['max_current_ma'])}f
#define NEXUS_MAX_PWM_PERCENT {int(safety['max_pwm_percent'])}
#define NEXUS_MAX_MOTOR_TEST_DURATION_MS {int(safety['max_motor_test_duration_ms'])}
#define NEXUS_TELEMETRY_INTERVAL_MS {int(profile['telemetry']['interval_ms'])}
"""

output = project_dir / "include" / "nexus_hardware_profile.generated.h"
if not output.exists() or output.read_text(encoding="utf-8") != content:
    output.parent.mkdir(parents=True, exist_ok=True)
    output.write_text(content, encoding="utf-8", newline="\n")
print(f"NEXUS PROFILE: {profile['profile_id']} -> {output.name}")
