[platformio]
default_envs = nexus-goouuu-esp32-s3-n16r8

[env:nexus-goouuu-esp32-s3-n16r8]
platform = espressif32
board = nexus-goouuu-esp32-s3-n16r8
framework = arduino
monitor_speed = 115200
monitor_dtr = 0
monitor_rts = 0
upload_protocol = esp-builtin
lib_deps =
  robtillaart/INA226 @ ^0.6.6
build_unflags =
  -std=gnu++11
build_flags =
  -std=gnu++17
  -D NEXUS_DEVICE_ID=\"nexus-demo-esp32\"
  -D NEXUS_HARDWARE_MODEL_ID=\"nexus-s3-ina226-l298n-motor-rig-v1\"
  -D NEXUS_MAX_PWM_PERCENT=80

[env:nexus-goouuu-esp32-s3-n16r8-baseline]
extends = env:nexus-goouuu-esp32-s3-n16r8
build_flags =
  ${env:nexus-goouuu-esp32-s3-n16r8.build_flags}
  -D NEXUS_ENABLE_BASELINE_CONTROL=1
